### ISSUE TITLE
Possible screen size problem

### ISSUE THREAD

**Issue by hermondy** [Fumi24/RunesReformed#1]
Works like a charm on my laptop (1366x768 resolution) but not at all on my pc (1600x1080 resolution). When i lower the resolution on my pc then it works.

**Comment by Fumi24** [comment]
Could you tell me how it doesnt work? the code doesnt use resolution in anyway so it should work on 800x600 and 4k

**Comment by hermondy** [comment]
All i know is the program works without any error but it wont pick the runes on my pc. When i get home i will try to find why this happens. Thanks.
