### ISSUE TITLE
Don't working on new patch

### ISSUE THREAD

**Issue by makeouthill1** [Fumi24/RunesReformed#10]
When i click "page" there is nothing.

**Comment by Fumi24** [comment]
Champion.gg's api is having downtime (which is where i get the runes from), there is nothing i can do atm to fix this.

**Comment by fahdoviix** [comment]
The Champion.gg's api is back ? does the program work now ?

**Comment by MarcusKoen** [comment]
Hey Fumi, I just wanted to let you know that champion's api is back online and that your program is working fine again!

**Comment by Fumi24** [comment]
Thx for the info, i Will try to work on a solution if This happens again.
