### ISSUE TITLE
Make 'Delete Current Page' checkbox persist state when the program is re-opened

### ISSUE THREAD

**Issue by mewtlu** [Fumi24/RunesReformed#11]

**Comment by mewtlu** [comment]
Looks fixed by commit [7738d64e2aa6f4f4c81311a9a8541166e670542c](https://github.com/Fumi24/RunesReformed/commit/7738d64e2aa6f4f4c81311a9a8541166e670542c)

**Comment by Fumi24** [comment]
Not live yet, will make it public in a few days if there are no major changes.
