### ISSUE TITLE
Can't select champ pages again

### ISSUE THREAD

**Issue by MarcusKoen** [Fumi24/RunesReformed#12]
Can't seem to select a champ's pages, Champion.gg api is running and im updated to latest version

**Comment by GrimLoki** [comment]
I have the same issue as MarcusKoen..I can select the champ but there are no rune pages to choose...please help.

Thanks

**Comment by Fumi24** [comment]
I believe this is fixed, my bad on this one.

**Comment by MarcusKoen** [comment]
It is fixed thanks! Appreciate the quick response!
