### ISSUE TITLE
Mitigate missing API feed data

### ISSUE THREAD

**Issue by Codecasaurus** [Fumi24/RunesReformed#13]
Some champion's sub-pages are missing at the moment I write this because champion.gg does not have data for them.  This could be mitigated a few ways but adding alternative supplying APIs could be a solution and likely the easiest to implement.
![missing](https://user-images.githubusercontent.com/6042227/48970205-af214380-efd7-11e8-8bfc-3ec20af44542.png)
![notmissing](https://user-images.githubusercontent.com/6042227/48970206-af214380-efd7-11e8-8d8e-f766d1d97596.png)
![image](https://user-images.githubusercontent.com/6042227/48970218-cbbd7b80-efd7-11e8-8a25-2f65be9c3d42.png)

**Comment by Fumi24** [comment]
This is completly true, but as of right now i dont know of any other external site with an API like champion.gg, i could scrape pages like u.gg for their information but it wouldnt be sustainable like champion.gg is. If you guys know of any site with a public API i would be more than happy to implement it.

**Comment by etheaven** [comment]
> This is completly true, but as of right now i dont know of any other external site with an API like champion.gg, i could scrape pages like u.gg for their information but it wouldnt be sustainable like champion.gg is. If you guys know of any site with a public API i would be more than happy to implement it.

Mind releasing the API which gathers the runes and champions?

**Comment by Fumi24** [comment]
@etheaven I just simply gather the data from champion.gg's api, nothing fancy.

**Comment by danalec** [comment]
Yuumi is missing
