### ISSUE TITLE
How do i run this?

### ISSUE THREAD

**Issue by Xetarus** [Fumi24/RunesReformed#17]
How do i run this program? On the reddit post there is a "see it in action" video where it opens as a little window where you can choose the champion but when i try to open it, it opens in microsoft visual studio.

**Comment by Fumi24** [comment]
Hello, the program was decapitated and is no longer working, may I suggest https://github.com/pipe01/legendary-rune-maker as pipe updates is quite frequently

**Comment by Xetarus** [comment]
thats sad to hear, but thank you for the substitute
