### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by madnesso** [Fumi24/RunesReformed#2]
when i click set runes nothing happens at all

**Comment by Fumi24** [comment]
Do you have an empty rune page? if you are full on pages nothing will happen.

**Comment by madnesso** [comment]
nvm i was retarded it was working all along but i am used to it being on screen rather then "injecting" the page (some kind of sorcery xD ) great work man any chance you would add zoe though ?

**Comment by Fumi24** [comment]
added Faker's zoe page, should take 1 hour for it to be in the program
