### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by GabrielDuarteMG** [Fumi24/RunesReformed#4]
Please contact me ...
My email: gabriel160499@gmail.com

My facebook: https://www.facebook.com/Gabriields18

**Comment by Fumi24** [comment]
Contacted

**Comment by GabrielDuarteMG** [comment]
Hello bro,

I noticed that you have no time to continue the rune project.

So I decided to continue for you, giving some improvements in the interface
and in the methods that it works.

Send me any improvements you already wanted to put into it.

Here are some pictures of how the attached project is

Special Thanks, Gabriel Duarte

**Comment by Fumi24** [comment]
Im unsure what you mean by "So I decided to continue for you" you are welcome to make pull requests.

**Comment by GabrielDuarteMG** [comment]
So, thank u, and If you have a Idea for project talk to me

Em qui, 12 de abr de 2018 13:57, Jakob Boisen <notifications@github.com>
escreveu:
