### ISSUE TITLE
Not working on new patch

### ISSUE THREAD

**Issue by petekblaz** [Fumi24/RunesReformed#5]
Can it be updated for latest patch?

**Comment by GeertHauwaerts** [comment]
The runes [API URL](https://wepapirunepages.azurewebsites.net/api/values) only return a very small subset of pages.

**Comment by Fumi24** [comment]
> The runes API URL only return a very small subset of pages.

This is because Champion.gg only has a few pages for 8.11.

**Comment by Knockichu** [comment]
when will everything work normally?

**Comment by Fumi24** [comment]
There is an error with my amazon server doing the runes, i will try to get champion.gg to work.

**Comment by Fumi24** [comment]
Fixed 🥇 Currently only have Champion.gg runes
