### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lejkoal11** [Fumi24/RunesReformed#6]
Still not working for me

**Comment by Fumi24** [comment]
Are you using 1.3.8?

**Comment by lejkoal11** [comment]
Yes

**Comment by Fumi24** [comment]
Can you explain or take a picture of the error/thing thats not working?

**Comment by lejkoal11** [comment]
Oh, the program start working i just restarted my computer but where are the Runeforge.gg set ? :/

**Comment by Fumi24** [comment]
i had to remove them since they were crashing the amazon server, i will try to get them back either today or tomorrow.

**Comment by lejkoal11** [comment]
Ok, thank you ^^

**Comment by Fumi24** [comment]
They should be there now, some of the pages are not update to use Nimbus Cloak or Ultimate Hunter, i've coded it so if the page uses Ultimate Hat (gone) it will automatically use Nimbus Cloak.
