### ISSUE TITLE
Runeforge gg

### ISSUE THREAD

**Issue by lejkoal123** [Fumi24/RunesReformed#7]
I just want to ask where are the runeforge gg sets. I miss them so much, while using webpage my computer is lagging, so only your program is the best way for me to set the best runes before the match. I appreciate your hard work and thank you for this great program. (sorry for my bad english)

**Comment by Fumi24** [comment]
I could add the runeforge.gg pages back, but they simply cause too many problems. There is no offical API to get the pages from so what i did was scrape the HTML page which gives me Pagename and all the runes in text form aka Electrocute while this is fine everytime riot changes and ID of a runes or the position of a rune i will have to update my code to reflect that. I would love to support all the data based leauge sites out there but the fact is Champion.gg is the only one that put in a little work for others to do so.

I know [https://runebook.app/](Runebook) has runeforge.gg pages, go check them out :)

**Comment by lejkoal123** [comment]
Thank you so much. I was looking for site like that for a month :D but that doesn't mean i am not going to use your program. Good luck ^^

**Comment by Fumi24** [comment]
Update - I've fixed the problems in getting runeforge.gg pages, so you should now (or in like 5 mins) see runeforge.gg pages inside the program. 👍
