### ISSUE TITLE
Problem with wrong runes for champions  ?

### ISSUE THREAD

**Issue by AbdelrahmanMohamedDesoky** [Fumi24/RunesReformed#9]
Problems with runeReformed

1: Wrong runes all the the time
2: Where do you get your Runes Data from ?
3: Sorry.

**Comment by Fumi24** [comment]
![I have attached said picture here](https://user-images.githubusercontent.com/21745301/43165165-8e54aa06-8f93-11e8-9afa-a5823be1b3ee.jpg) you have liked this on facebook, so why are you breaking your own rules

**Comment by AbdelrahmanMohamedDesoky** [comment]
Ok, Let's be honest here, that wasn't a good day for me.

Can you explain to me from where do you get your rune pages from ? Because I literly got wrong runes for my Champion like 5 times in a row.


P.S : If you don't know a good site to get the runes from , i suggest trying https://runeforge.gg/


P.S 2 : Is that better now ?

**Comment by AbdelrahmanMohamedDesoky** [comment]
Sorry.
